### ISSUE TITLE
[Bug] Error trying to login with 2FA: x is not a function

### ISSUE THREAD

**Issue by FranzMari** [AmruthPillai/Reactive-Resume#2827]
### Is there an existing issue for this?

- [x] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Describe the bug you're experiencing

Trying to access my account on rxresu.me, I get an error on the [page](https://rxresu.me/auth/verify-2fa) where I'm supposed to insert my 2FA.

Here's the error shown in the page:
<img width="638" height="523" alt="Image" src="https://github.com/user-attachments/assets/f986cc04-589f-4fce-be2a-dbef3790c01b" />

and here's the console content
<img width="896" height="255" alt="Image" src="https://github.com/user-attachments/assets/3b1c1c3f-6cb5-4159-a7d1-67b9e3c09402" />

### What template are you using?

None

**Comment by foegra** [comment]
Having same issue with self hosted version. Working with version `v5.0.11`, broke in `v5.0.12`

Docker logs:

```
TypeError: f is not a function
    at file:///app/.output/server/_libs/input-otp.mjs:332:42
    at Object.useMemo (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:11328:16)
    at exports.useMemo (file:///app/.output/server/_libs/@ai-sdk/react+%5B...%5D.mjs:8665:33)
    at file:///app/.output/server/_libs/input-otp.mjs:332:24
    at renderWithHooks (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:11951:18)
    at renderElement (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:12218:13)
    at retryNode (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:12379:12)
    at renderNodeDestructive (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:12277:235)
    at finishFunctionComponent (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:11967:232)
    at renderElement (file:///app/.output/server/_libs/@tanstack/react-router+%5B...%5D.mjs:12017:4)
```

**Comment by amruthpillai** [comment]
This should be resolved as of the latest image, and also on https://rxresu.me. Seems like there was some issue with `input-otp` library all of a sudden, just went back to good ol' text boxes for now.
